# Configuration file for str2table
# You can use conf_name to set the name of the configuration
# So you can include multiple configuration in one file
[conf_name]
# input path, use console input if not set
input = "input.txt"

# seperation char, default is ' '
seperation = "#"

# Is auto parse, default is true
is_auto = true

# force parse line, use a array, default is []
# the following example means, force the first line to string,
# the second line to fourth line to integer
force_parse.line = [[1, 1, 's'], [2, 4, 'i']]

# force parse column, use a array, default is [], same as line
force_parse.column = [[1, 1, 's'], [2, 2, 'i']]

# export path, use console output if not set
export = "output.txt"

# export color by line, use a array, default is []
# the following example means, set the first line to red,
# the second line to fourth line to green, the third line to blue
export_color.line = [[1, 1, 'r'], [2, 4, 'g']]

# export color by column, use a array, default is [], same as line
export_color.column = [[1, 1, 'r'], [2, 2, 'g']]

# export subtable line, use a array, default export the whole line
# the following example means, export the first line and third line
export_subtable.line = [1, 3]

# export subtable column, use a array, default export the whole column
# the following example means, export the first column and third column
export_subtable.column = [1, 3]

# not export subtable line, use a array, default is [] means export the whole column
# the following example means, not export the first and third line
# can't set it with export_subtable.line
# not_export_subtable.line = [1, 3]

# not export subtable column, use a array, default is [] means export the whole line
# the following example means, not export the first and third column
# can't set it with export_subtable.column
# not_export_subtable.column = [1, 3]

# use configuration from other configuration module, use config from this configuration first if conflict
# if you use . as path, then find the conf_name in this file
# configuration = ["path/to/file", "conf_name"]
