[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
ibig = "0.3.6"
xlsxwriter = "0.6.1"
toml = "0.8.14"
regex = "1.10.5"
once_cell = "1.19.0"
